apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-prometheus
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/ssd/prometheus"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-grafana
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/ssd/grafana"
