apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-nfs-share
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/ssd/mongodb"
