apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: mongodb
spec:
  serviceName: mongo
  replicas: 3
  selector:
    matchLabels:
      role: mongo
      environment: dev
  template:
    metadata:
      labels:
        role: mongo
        environment: dev
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo:4.4-rc
          command:
            - mongod
          args:
            - --dbpath=/data/db
            - --replSet=rs0
            - --port=27017
            - --bind_ip=0.0.0.0
          ports:
            - containerPort: 27017
              name: database
          volumeMounts:
            - name: mongo-pvc
              mountPath: /data/db
        - name: mongo-sidecar
          image: teambasezero/mongo-k8s-sidecar
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "role=mongo,environment=dev"
            # - name: MONGODB_USERNAME
            #   value: admin
            # - name: MONGODB_PASSWORD
            #   value: password
            # - name: MONGODB_DATABASE
            #   value: local
  volumeClaimTemplates:
  - metadata:
      name: mongo-pvc
      namespace: mongodb
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
