apiVersion: v1
kind: Service
metadata:
  name: nextcloud-mariadb
  namespace: nextcloud
  labels:
    app: nextcloud
spec:
  clusterIP: None
  ports:
  - port: 3306
  selector:
    app: nextcloud
    component: mariadb
