apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-share
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/ssd/nextcloud_app"
