apiVersion: v1
kind: Service
metadata:
  labels:
    app: nextcloud
    component: redis
  name: nextcloud-redis
  namespace: nextcloud
spec:
  ports:
  - port: 6379
  selector:
    app: nextcloud
    component: redis
